### PR TITLE
Added instructions for Solaris or illumos

### PR DESCRIPTION
**Pull request by dewi-ny-je**

### CODE REVIEW

**Comment by lefcha** [comment]
Thank you very much for the contribution.

But I decided at some point that I don't want to include separate instructions for the several different systems, like popular Linux distributions, the main BSD operating systems, etc. mainly because I can't keep these instructions updated.

So I decided to just provide some basic instructions for Linux along with a simple/generic make file, that should work if one has installed Lua and the requirement libraries in their default installation place.

**Comment by lefcha** [comment]
I enabled the Wiki since a couple of days ago, as some people wanted to [contribute some custom functions](https://github.com/lefcha/imapfilter/issues/177#issuecomment-504467200).

It would probably be a good idea to include the Solaris/illumos, or in general other OS-specific build instructions, in the Wiki, too.  So feel free to add a page with the instructions there, if you want.

**Comment by dewi-ny-je** [comment]
I'm not using OmniOS/illumos anymore, so it would be difficult for me to verify whatever I could write in the Wiki. 
I guess that OmniOS users will have to figure it out themselves.

**Comment by lefcha** [comment]
That's totally fine, someone will probably do it sooner or later.

> I'm not using OmniOS/illumos anymore, so it would be difficult for me to verify whatever I could write in the Wiki.

This is the main reason I don't want to add special build instructions inside the README; because I can't maintain the instructions myself and sooner or later they become obsolete and don't work anymore.

**Pull request closed without merging**
